ci: add check remote buildkitd step in e2e tests
Signed-off-by: Justin Chadwell <me@jedevc.com>

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -142,8 +142,31 @@ jobs:
           docker run -d --privileged \
             --name=remote-buildkit \
             -p 1234:1234 \
+            --health-cmd "buildctl debug workers" \
+            --health-interval 1s \
             ${{ matrix.buildkit }} \
+            --addr unix:///run/buildkit/buildkitd.sock \
             --addr tcp://0.0.0.0:1234
+      -
+        name: Check remote buildkitd
+        if: matrix.driver == 'remote'
+        run: |
+          try=0
+          max=10
+          until [ "$(docker container inspect remote-buildkit --format '{{ .State.Health.Status }}')" = "healthy" ]; do
+            if [ $try -gt $max ]; then
+              echo >&2 "healthcheck failed after $max trials"
+              exit 1
+            fi
+            sleep $(awk "BEGIN{print (100 + $try * 20) * 0.002}")
+            try=$(expr $try + 1)
+          done
+      -
+        name: Remote container inspect
+        if: always() && matrix.driver == 'remote'
+        run: |
+          docker container inspect remote-buildkit
+          docker logs remote-buildkit
       -
         name: Test
         run: |
